# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/axelo/OneDrive/Skrivebord/NyFPGA/NyFPGA.srcs/sources_1/bd/design_1/ip/design_1_AlgM_0_0/design_1_AlgM_0_0.xci
# IP: The module: 'design_1_AlgM_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: C:/Users/axelo/OneDrive/Skrivebord/NyFPGA/NyFPGA.srcs/sources_1/Alg_cal.srcs/sources_1/ip/cordic_0/cordic_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==cordic_0 || ORIG_REF_NAME==cordic_0} -quiet] -quiet

# IP: C:/Users/axelo/OneDrive/Skrivebord/NyFPGA/NyFPGA.srcs/sources_1/bd/design_1/ip/design_1_AlgM_0_0/design_1_AlgM_0_0.xci
# IP: The module: 'design_1_AlgM_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: C:/Users/axelo/OneDrive/Skrivebord/NyFPGA/NyFPGA.srcs/sources_1/Alg_cal.srcs/sources_1/ip/cordic_0/cordic_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==cordic_0 || ORIG_REF_NAME==cordic_0} -quiet] -quiet
