set_property PACKAGE_PIN E22 [get_ports reset]
set_property PACKAGE_PIN H14 [get_ports Vaux1_v_n]
set_property IOSTANDARD LVCMOS33 [get_ports Vaux1_v_n]
set_property IOSTANDARD LVCMOS33 [get_ports Vaux1_v_p]
set_property IOSTANDARD LVCMOS33 [get_ports reset]
set_property IOSTANDARD LVCMOS33 [get_ports {address[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {address[0]}]
set_property PACKAGE_PIN AB22 [get_ports {address[1]}]
set_property PACKAGE_PIN Y21 [get_ports {address[0]}]
set_property PACKAGE_PIN AA18 [get_ports CS]
set_property PACKAGE_PIN V9 [get_ports dataValidOut]
set_property PACKAGE_PIN V7 [get_ports dest_pulse]
set_property PACKAGE_PIN AB20 [get_ports MISO]
set_property PACKAGE_PIN AA21 [get_ports PosUpdateFlag]
set_property PACKAGE_PIN AB18 [get_ports SCK]
set_property PACKAGE_PIN AA20 [get_ports start]
set_property PACKAGE_PIN W9 [get_ports TOF_ready]
set_property IOSTANDARD LVCMOS33 [get_ports CS]
set_property IOSTANDARD LVCMOS33 [get_ports dataValidOut]
set_property IOSTANDARD LVCMOS33 [get_ports dest_pulse]
set_property IOSTANDARD LVCMOS33 [get_ports MISO]
set_property IOSTANDARD LVCMOS33 [get_ports PosUpdateFlag]
set_property IOSTANDARD LVCMOS33 [get_ports SCK]
set_property IOSTANDARD LVCMOS33 [get_ports start]
set_property IOSTANDARD LVCMOS33 [get_ports TOF_ready]

set_property CONFIG_MODE SPIx4 [current_design]

set_property BITSTREAM.GENERAL.COMPRESS TRUE [current_design]
set_property BITSTREAM.CONFIG.CONFIGRATE 33 [current_design]

set_property IOSTANDARD LVCMOS33 [get_ports {currentStateDebug[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {currentStateDebug[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {currentStateDebug[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {currentStateDebug[0]}]
set_property PACKAGE_PIN Y6 [get_ports {currentStateDebug[0]}]
set_property PACKAGE_PIN AA8 [get_ports {currentStateDebug[1]}]
set_property PACKAGE_PIN R6 [get_ports {currentStateDebug[2]}]
set_property PACKAGE_PIN AB7 [get_ports {currentStateDebug[3]}]
